'use strict';
const path=require('node:path'),os=require('node:os');
const {spawn}=require('node:child_process');
const device=require('./device.cjs');
const definitions=[
 {id:'smtc-music',name:'音乐同步 · SMTC Music',description:'当前播放信息、歌词、封面和媒体控制',port:17865,icon:'music',color:'#2eb86e',apps:['holocubic-smtc-music','smtc_music','smtc-music']},
 {id:'pc-monitor',name:'电脑监控',description:'CPU、GPU、内存、温度与网络数据',port:17322,icon:'cpu',color:'#955cec',apps:['holo_pc_monitor','holo-pc-monitor']},
 {id:'desktop-mirror',name:'桌面投屏',description:'显示器或指定区域 · 320 × 240 WebSocket',port:8787,icon:'monitor',color:'#24b5c0',apps:['pc_mirror','desktop_mirror','desktop-mirror']},
 {id:'holopet',name:'Holopet',description:'ChatGPT 与常见 AI 的工作状态同步',port:17321,icon:'pet',color:'#efa451',apps:['holopet','holo_pet','clawd_monitor']},
 {id:'codex-core',name:'Codex Buddy',description:'Codex 事件类型与工作状态',port:8788,icon:'code',color:'#657b9a',apps:['codex_buddy','codex-buddy']}
];
const forApp=id=>definitions.find(d=>d.apps.includes(String(id||'').trim().toLowerCase()));
class Companions{
 constructor({nativeCall,prefs,savePrefs,emit,log,dataDir,appDir}){Object.assign(this,{nativeCall,prefs,savePrefs,emit,log,dataDir,appDir});this.music=null;this.manual=new Set();this.jobs=new Map();this.configured=new Map();this.lastApp=new Map();this.attempts=new Map();this.errors=new Map();this.closing=false;}
 async health(def){try{const r=await fetch('http://127.0.0.1:'+def.port+'/health',{signal:AbortSignal.timeout(900)});if(!r.ok)return false;const d=await r.json();return d.ok===true||d.status==='ok'||d.status==='healthy'}catch{return false}}
 async snapshot(){const owned=await this.nativeCall('service-status');const statuses=await Promise.all(definitions.map(async d=>{const local=d.id==='smtc-music'?!!this.music:owned.some(x=>x.id===d.id&&x.running);const running=await this.health(d);return {...d,running,owned:local,external:running&&!local,autoStart:!!this.prefs().serviceAutoStart?.[d.id],message:this.errors.get(d.id)||(running?(local?'运行中':'由其他程序提供服务'):'已停止'),manuallyStopped:this.manual.has(d.id)}}));return {services:statuses,autoCompanion:this.prefs().autoCompanion!==false}}
 async start(id,manual=true){if(manual)this.manual.delete(id);if(this.jobs.has(id))return this.jobs.get(id);const d=definitions.find(x=>x.id===id);if(!d)throw Error('未知电脑服务');const work=(async()=>{try{if(await this.health(d))return true;this.errors.delete(id);
  if(id==='smtc-music'){const child=spawn(path.join(this.appDir,'services','smtc','smtc-bridge.exe'),[],{windowsHide:true,cwd:this.dataDir,env:{...process.env,SMTC_BRIDGE_PORT:String(d.port)},stdio:'ignore'});this.music=child;child.on('error',e=>{this.errors.set(id,e.message);this.log('音乐服务：'+e.message)});child.on('exit',()=>{if(this.music===child)this.music=null;this.emit('services-changed',null)});for(let n=0;n<20;n++){if(await this.health(d))break;await new Promise(r=>setTimeout(r,250));}if(!await this.health(d))throw Error('音乐服务未能启动');}
  else{if(id==='desktop-mirror'&&this.prefs().mirror)await this.nativeCall('mirror-config',this.prefs().mirror);await this.nativeCall('service-start',{service:id});}
  this.log(d.name+' 已启动');this.emit('services-changed',null);return true;
 }catch(e){this.errors.set(id,e.message);throw e}finally{this.jobs.delete(id)}})();this.jobs.set(id,work);return work;}
 async stop(id){this.manual.add(id);for(const [key,value]of this.configured)if(value.service===id)this.configured.delete(key);await this.jobs.get(id)?.catch(()=>{});if(id==='smtc-music'){if(!this.music){if(await this.health(definitions[0]))throw Error('该服务由其他程序启动，请在原程序中停止');return}this.music.kill();this.music=null;}else{const own=await this.nativeCall('service-status');if(!own.some(s=>s.id===id&&s.running)&&await this.health(definitions.find(d=>d.id===id)))throw Error('该服务由其他程序启动，请在原程序中停止');await this.nativeCall('service-stop',{service:id})}this.errors.delete(id);this.emit('services-changed',null);this.log('电脑服务已停止：'+id)}
 async prepare(address,appId){const d=forApp(appId);if(!d||this.prefs().autoCompanion===false)return;await this.start(d.id);if(d.id==='desktop-mirror'){const local=await device.localAddress(address);const location='/sd/apps/'+appId+'/config.json';let prior={};try{prior=await device.request(address,'/api/system/fs/file?path='+encodeURIComponent(location))}catch{}await device.request(address,'/api/system/fs/upload?path='+encodeURIComponent(location),'PUT',{...(typeof prior==='object'?prior:{}),url:'ws://'+local+':8787',ws_buffer:65536});}}
 async observe(address,state,force=false){if(this.closing||this.prefs().autoCompanion===false&&!force)return;const id=state?.current_app?.id||'',d=forApp(id),previous=this.lastApp.get(address);this.lastApp.set(address,id);if(!d)return;if(previous!==id||force)this.manual.delete(d.id);if(this.manual.has(d.id))return;const route=state.current_route_base||'/'+id;const local=await device.localAddress(address);const key=address+'|'+id+'|'+route+'|'+local;const saved=this.configured.get(address);if(!force&&saved?.key===key)return;const attempt=this.attempts.get(key);if(attempt?.pending||!force&&attempt&&Date.now()-attempt.time<15000)return;this.attempts.set(key,{time:Date.now(),pending:true});
  try{await this.start(d.id,false);if(this.manual.has(d.id))return;this.emit('companion',{state:'working',message:'正在自动配置 '+d.name,device:address});await this.configure(address,id,route,local,d);this.configured.set(address,{key,service:d.id});this.errors.delete(d.id);this.log(d.name+' 已自动配置 '+address+' → '+local+':'+d.port);this.emit('companion',{state:'done',message:d.name+' 已自动启动并配置',device:address});}
  catch(e){this.errors.set(d.id,'自动配置失败：'+e.message);this.log(d.name+' 自动配置失败：'+e.message);this.emit('companion',{state:'error',message:d.name+'：'+e.message,device:address});if(force)throw e}
  finally{this.attempts.set(key,{time:Date.now(),pending:false});this.emit('services-changed',null)}
 }
 async configure(address,id,route,local,d){const get=p=>device.request(address,p),send=(p,body)=>device.request(address,p,'POST',body);const query=new URLSearchParams({host:local,port:String(d.port)});
  if(d.id==='smtc-music'){const p=route+'/api/config',v=await get(p);const next={host:local,port:d.port,poll_ms:v.poll_ms??1000,timeout_ms:v.timeout_ms??2500,status_path:v.status_path||'/status',control_path:v.control_path||'/control',serial_log:v.serial_log!==false};if(v.host!==local||Number(v.port)!==d.port)await send(p,next);const saved=await get(p);if(saved.host!==local||Number(saved.port)!==d.port)throw Error('音乐服务地址未能保存');return;}
  if(d.id==='pc-monitor'){const v=await get(route+'/api/state');query.set('path','/sse');query.set('layout',v.layout||'default');query.set('cpu_name',v.cpu_name||os.cpus()[0]?.model||'Windows CPU');query.set('gpu_name',v.gpu_name||'');query.set('accent_color',v.accent_color||'#44ccff');if(v.host!==local||Number(v.port)!==d.port||v.path!=='/sse')await get(route+'/api/save?'+query);const saved=await get(route+'/api/state');if(saved.host!==local||Number(saved.port)!==d.port)throw Error('电脑监控地址未能保存');return;}
  if(d.id==='holopet'){query.set('path','/events');const v=await get(route+'/api/state');if(v.host!==local||Number(v.port)!==d.port||v.path!=='/events')await get(route+'/api/save?'+query);const saved=await get(route+'/api/state');if(saved.host!==local||Number(saved.port)!==d.port)throw Error('Holopet 地址未能保存');return;}
  if(d.id==='desktop-mirror'){if(id==='pc_mirror'){const v=await get(route+'/api/state');if(v.host!==local||Number(v.port)!==d.port)await get(route+'/api/save?'+query);const saved=await get(route+'/api/state');if(saved.host!==local||Number(saved.port)!==d.port)throw Error('投屏地址未能保存');}else await this.prepare(address,id);return;}
  // Legacy Codex Buddy uses the fixed compatible port; it has no configurator in the old app.
 }
 async autoStart(){for(const d of definitions){if(this.prefs().serviceAutoStart?.[d.id])try{await this.start(d.id,false)}catch(e){this.log(d.name+' 自启动失败：'+e.message)}}}
 close(){this.closing=true;this.music?.kill()}
}
module.exports={Companions,definitions,forApp};
