'use strict';
(()=>{
 const fm={address:'',path:'/sd',entries:[],selected:new Set(),history:[],index:-1,sort:'name',ascending:true,filter:'',tree:new Map(),expanded:new Set(['/sd']),clipboard:null,loading:false,seq:0,anchor:0};
 let transfers=[],queueOpen=false,queueFilter="all";
 const bytes=n=>{if(!Number.isFinite(n)||n<0)return '—';const units=['B','KB','MB','GB'];let i=0;while(n>=1024&&i<3){n/=1024;i++;}return n.toFixed(i?1:0)+' '+units[i];};
 const parent=p=>p==='/sd'?'/sd':p.slice(0,p.lastIndexOf('/'));
 const ficon=entry=>entry.is_dir?'<span class="fm-folder">▰</span>':icon(/\.(png|jpg|jpeg|gif|webp|bmp)$/i.test(entry.name)?'image':/\.(lua|js|json|c|h|py)$/i.test(entry.name)?'code':'file');
 const command=(id,label,ico,disabled=false)=>`<button class="fm-command" data-fm="${id}" ${disabled?'disabled':''}>${ico?icon(ico):''}<span>${label}</span></button>`;
 const selected=()=>fm.entries.filter(x=>fm.selected.has(x.path));
 function sorted(){return fm.entries.filter(x=>x.name.toLowerCase().includes(fm.filter.toLowerCase())).sort((a,b)=>{if(a.is_dir!==b.is_dir)return a.is_dir?-1:1;const av=fm.sort==='type'?(a.is_dir?'':a.name.split('.').pop()):a[fm.sort],bv=fm.sort==='type'?(b.is_dir?'':b.name.split('.').pop()):b[fm.sort];return (typeof av==='number'?av-bv:String(av||'').localeCompare(String(bv||''),'zh-CN',{numeric:true}))*(fm.ascending?1:-1);});}
 async function open(){closeModal();closeDrawer();$('#deviceMenu').classList.add('hidden');if(fm.address!==state.prefs.active){fm.address=state.prefs.active;fm.path='/sd';fm.tree.clear();fm.history=[];fm.index=-1;fm.clipboard=null;}state.page='files';$('#main').classList.remove('browser-mode');$('#main').classList.add('files-mode');await layout();render();await navigate(fm.path,fm.index<0);}
 function breadcrumbs(){const parts=fm.path.split('/').filter(Boolean);return parts.map((p,i)=>`<button data-fm-path="/${parts.slice(0,i+1).join('/')}">${esc(i===0?'SD 卡':p)}</button>`).join('<span>›</span>');}
 function treeNode(p,name,depth=0){const opened=fm.expanded.has(p),children=fm.tree.get(p)||[];return `<div class="fm-tree-row ${fm.path===p?'active':''}" style="padding-left:${10+depth*14}px"><button class="fm-twisty" data-fm-tree="${esc(p)}">${opened?'⌄':'›'}</button><button data-fm-path="${esc(p)}"><span class="fm-folder">▰</span>${esc(name)}</button></div>${opened?children.filter(x=>x.is_dir).map(x=>treeNode(x.path,x.name,depth+1)).join(''):''}`;}
 function render(){if(state.page!=='files')return;$('#main').innerHTML=`<div class="fm-device-line" data-no-i18n><strong>${esc(dev().name)}</strong><span>${esc(fm.address)}</span></div><section class="fm-explorer"><div class="fm-tools">${command('mkdir','新建文件夹','plus')}${command('upload','上传文件','upload')}${command('upload-folder','上传文件夹','folder')}${command('download','下载','download',!fm.selected.size)}<i></i>${command('copy','复制','file',!fm.selected.size)}${command('cut','剪切','tool',!fm.selected.size)}${command('paste','粘贴','',!fm.clipboard)}${command('rename','重命名','',fm.selected.size!==1)}${command('delete','删除','trash',!fm.selected.size)}<div class="fm-tool-spacer"></div>${command('queue','传输队列','download')}</div><div class="fm-address-row"><button class="icon-button" data-fm="back" title="后退" ${fm.index<=0?'disabled':''}>${icon('back')}</button><button class="icon-button" data-fm="forward" title="前进" ${fm.index>=fm.history.length-1?'disabled':''}>${icon('forward')}</button><button class="icon-button" data-fm="up" title="上级目录" ${fm.path==='/sd'?'disabled':''}>↑</button><button class="icon-button" data-fm="refresh" title="刷新">${icon('refresh')}</button><div class="fm-address" title="双击编辑路径">${icon('folder')}<div id="fmCrumbs">${breadcrumbs()}</div><input id="fmPathInput" class="hidden" value="${esc(fm.path)}" aria-label="目录路径"><button data-fm="address" title="编辑路径">⌨</button></div><div class="fm-search">${icon('search')}<input id="fmSearch" placeholder="搜索当前文件夹" value="${esc(fm.filter)}"></div></div><div class="fm-body"><aside class="fm-tree"><h3>此设备</h3><div id="fmTree">${treeNode('/sd','SD 卡')}</div><div class="fm-tree-note">文件与设备实时同步</div></aside><div class="fm-list-area" id="fmListArea"><table class="fm-table"><thead><tr><th class="fm-check"><input id="fmSelectAll" type="checkbox" aria-label="全选"></th>${[['name','名称'],['type','类型'],['size','大小'],['modified','修改时间']].map(([k,t])=>`<th><button data-fm-sort="${k}">${t} ${fm.sort===k?(fm.ascending?'↑':'↓'):''}</button></th>`).join('')}</tr></thead><tbody id="fmRows"></tbody></table><div class="fm-drop-hint" id="fmDropHint">${icon('upload')}拖入电脑文件或文件夹，上传到当前目录</div></div></div><footer class="fm-footer"><span id="fmStatus"></span><span>${fm.clipboard?`${fm.clipboard.move?'待移动':'已复制'} ${fm.clipboard.paths.length} 项`:fm.loading?'正在读取…':'Ctrl 多选 · Shift 连选 · 右键操作'}</span></footer></section>`;renderRows();syncChrome();updateBack();}
 function renderRows(){if(!$('#fmRows'))return;const entries=sorted();$('#fmRows').innerHTML=entries.map((e,i)=>`<tr data-fm-row="${esc(e.path)}" data-index="${i}" class="${fm.selected.has(e.path)?'selected':''} ${fm.clipboard?.move&&fm.clipboard.paths.includes(e.path)?'cut':''}"><td class="fm-check"><input type="checkbox" tabindex="-1" ${fm.selected.has(e.path)?'checked':''}></td><td class="fm-name">${ficon(e)}<span>${esc(e.name)}</span></td><td>${e.is_dir?'文件夹':esc((e.name.includes('.')?e.name.split('.').pop().toUpperCase():'')+' 文件')}</td><td>${e.is_dir?'—':bytes(e.size)}</td><td>${e.modified?esc(typeof e.modified==='number'?new Date(e.modified*1000).toLocaleString():e.modified):'—'}</td></tr>`).join('')||`<tr><td colspan="5" class="fm-empty">${fm.loading?'正在读取文件…':fm.filter?'没有匹配的文件':'此文件夹为空'}<small>可以拖入文件，或点击“上传文件”</small></td></tr>`;updateSelection();}
 function updateBack(){}
 function updateSelection(){if(!$('#fmRows'))return;$$('[data-fm-row]').forEach(row=>{const yes=fm.selected.has(row.dataset.fmRow);row.classList.toggle('selected',yes);row.querySelector('input').checked=yes;});const items=selected();$('#fmStatus').textContent=`${fm.entries.length} 个项目${items.length?' · 已选择 '+items.length+' 项 · '+bytes(items.reduce((n,x)=>n+x.size,0)):''}`;for(const action of ['download','copy','cut','delete'])$(`[data-fm="${action}"]`).disabled=!items.length;$('[data-fm="rename"]').disabled=items.length!==1;$('#fmSelectAll').checked=!!sorted().length&&sorted().every(e=>fm.selected.has(e.path));}
 async function navigate(p,record=true){const seq=++fm.seq,address=fm.address;fm.loading=true;fm.selected.clear();renderRows();try{const result=await call('filesList',{address,path:p});if(seq!==fm.seq||address!==fm.address||state.page!=='files')return;fm.path=result.path;fm.entries=result.entries;fm.tree.set(fm.path,result.entries);if(!fm.tree.has('/sd')){const root=await call('filesList',{address,path:'/sd'});if(seq!==fm.seq)return;fm.tree.set('/sd',root.entries);}if(record&&fm.history[fm.index]!==fm.path){fm.history=fm.history.slice(0,fm.index+1);fm.history.push(fm.path);fm.index=fm.history.length-1;}fm.filter='';}catch(e){toast('读取目录失败：'+e.message);}finally{if(seq===fm.seq){fm.loading=false;render();}}}
 function selection(row,e){const p=row.dataset.fmRow,list=sorted(),i=Number(row.dataset.index);if(e.shiftKey){if(!e.ctrlKey)fm.selected.clear();for(let n=Math.min(fm.anchor,i);n<=Math.max(fm.anchor,i);n++)if(list[n])fm.selected.add(list[n].path);}else if(e.ctrlKey||e.target.matches('input')){fm.selected.has(p)?fm.selected.delete(p):fm.selected.add(p);fm.anchor=i;}else{fm.selected.clear();fm.selected.add(p);fm.anchor=i;}updateSelection();}
 function nameDialog(kind){const e=selected()[0],title=kind==='mkdir'?'新建文件夹':'重命名';modal(title,fm.path,`<form id="fmNameForm"><input id="fmName" value="${kind==='rename'?esc(e.name):'新建文件夹'}" autocomplete="off" aria-label="名称"><p class="small-note" id="fmNameError"></p><div class="modal-foot"><button type="button" class="btn" data-action="close-modal">取消</button><button type="submit" class="btn primary">确定</button></div></form>`);fm.nameAction=kind;fm.nameSource=e?.path;setTimeout(()=>{$('#fmName')?.focus();$('#fmName')?.select();},0);}
 async function action(id){if(id==='queue'){queueOpen=!queueOpen;renderQueue();return;}if(id==='back'||id==='forward'){const n=fm.index+(id==='back'?-1:1);if(n>=0&&n<fm.history.length){fm.index=n;await navigate(fm.history[n],false);}return;}if(id==='up')return navigate(parent(fm.path));if(id==='refresh')return navigate(fm.path,false);if(id==='address'){$('#fmCrumbs').classList.add('hidden');$('#fmPathInput').classList.remove('hidden');$('#fmPathInput').focus();$('#fmPathInput').select();return;}if(id==='mkdir'||id==='rename')return nameDialog(id);if(id==='copy'||id==='cut'){if(!selected().length)return;fm.clipboard={address:fm.address,paths:selected().map(e=>e.path),move:id==='cut'};render();toast(id==='copy'?'已复制，可进入目标目录粘贴':'已剪切，可进入目标目录粘贴');return;}if(id==='paste'){if(!fm.clipboard)return;if(fm.clipboard.address!==fm.address)throw Error('请返回原设备粘贴；跨设备请先下载再上传');await call('filesPaste',{...fm.clipboard,directory:fm.path});if(fm.clipboard.move)fm.clipboard=null;queueOpen=true;renderQueue();render();return;}if(id==='delete'){await call('filesDelete',{address:fm.address,paths:selected().map(e=>e.path)});queueOpen=true;renderQueue();return;}if(id==='download'){await call('filesDownload',{address:fm.address,paths:selected().map(e=>e.path)});queueOpen=true;renderQueue();return;}if(id==='upload'||id==='upload-folder'){await call('filesUpload',{address:fm.address,directory:fm.path,folder:id==='upload-folder'});queueOpen=true;renderQueue();return;}if(id==='open'){const e=selected()[0];if(!e)return;if(e.is_dir)return navigate(e.path);return call('filesOpen',{address:fm.address,path:e.path});}}
 function context(e,row){e.preventDefault();$('#fmContext')?.remove();if(row&&!fm.selected.has(row.dataset.fmRow)){fm.selected.clear();fm.selected.add(row.dataset.fmRow);updateSelection();}const menu=document.createElement('div');menu.id='fmContext';menu.className='fm-context';menu.innerHTML=(row?[['open','打开 / 预览'],['download','下载'],['copy','复制  Ctrl+C'],['cut','剪切  Ctrl+X'],['rename','重命名  F2'],['delete','删除  Delete']]:[['paste','粘贴  Ctrl+V'],['mkdir','新建文件夹'],['upload','上传文件'],['refresh','刷新']]).map(([id,text])=>`<button data-fm="${id}">${text}</button>`).join('');menu.style.left=Math.min(e.clientX,innerWidth-210)+'px';menu.style.top=Math.min(e.clientY,innerHeight-290)+'px';document.body.append(menu);}
 function renderQueue(){
  let panel=$('#fmQueue');if(!panel){panel=document.createElement('section');panel.id='fmQueue';panel.className='fm-queue hidden';panel.setAttribute('aria-label','传输队列');document.body.append(panel);}
  const wasOpen=!panel.classList.contains('hidden'),scroll=panel.querySelector('.fm-queue-list')?.scrollTop||0,expanded=[...panel.querySelectorAll('details[open]')].map(d=>d.dataset.job);
  const ended=t=>['已完成','已取消','失败','已跳过'].includes(t.state),active=transfers.filter(t=>!ended(t)),visible=transfers.filter(t=>queueFilter==='all'||(queueFilter==='active'?!ended(t):ended(t)));
  panel.className='fm-queue'+(queueOpen?'':' hidden');
  panel.innerHTML=`<header><div><b>传输队列</b><small>任务按顺序执行，关闭面板后继续传输</small></div><button class="icon-button" data-fm="queue" aria-label="关闭">${icon('x')}</button></header><nav class="fm-queue-tabs" aria-label="传输任务筛选">${[['all','全部',transfers.length],['active','进行中',active.length],['ended','已结束',transfers.length-active.length]].map(([id,name,count])=>`<button data-fm-filter="${id}" class="${queueFilter===id?'active':''}" aria-pressed="${queueFilter===id}"><span>${name}</span><b>${count}</b></button>`).join('')}</nav><div class="fm-queue-list">${visible.map(t=>{
   const terminal=ended(t),pct=t.state==='已完成'?100:t.total?Math.min(100,t.received/t.total*100):0,eta=t.speed&&t.total?Math.max(0,Math.ceil((t.total-t.received)/t.speed)):0,tone=t.state==='失败'?'error':t.state==='已完成'?'success':terminal?'muted':'active',items=t.items||[],multiple=Math.max(t.count||0,items.length)>1;
   return `<article class="fm-transfer ${tone}"><div class="fm-transfer-title"><span class="fm-transfer-icon">${icon(t.kind==='下载'?'download':t.kind==='上传'?'upload':t.kind==='删除'?'trash':'file')}</span><div class="fm-transfer-heading"><b data-no-i18n title="${esc(t.name)}">${esc(t.name)}</b><small><span>${esc(t.kind)}</span><i>·</i><span data-no-i18n>${esc(t.address)}</span></small></div><span class="fm-transfer-state">${esc(t.state)}</span></div><div class="fm-progress-row"><div class="fm-progress ${t.preparing?'preparing':''}"><i style="width:${pct}%"></i></div><strong>${t.preparing?'—':Math.floor(pct)+'%'}</strong></div><div class="fm-speed"><div><span>已传输</span><b>${bytes(t.received)} / <span>${t.preparing?'统计中':bytes(t.total)}</span></b></div><div><span>传输速度</span><b>${terminal?'—':bytes(t.speed||0)+'/s'}</b></div><div><span>剩余时间</span><b>${terminal?'—':eta?(eta<60?'剩余约 '+eta+' 秒':'剩余约 '+Math.ceil(eta/60)+' 分钟'):t.preparing?'统计中':'—'}</b></div></div>${t.error?`<p class="fm-error">${esc(t.error)}</p>`:''}<div class="fm-transfer-footer"><span class="fm-file-count"><span>文件</span> <b>${t.done||0} / ${t.count||'—'}</b>${t.skipped?` · <span>跳过 ${t.skipped} 项</span>`:''}</span><div class="fm-transfer-actions">${!terminal?`<button data-fm-cancel="${t.id}">取消</button>`:''}${['失败','已取消'].includes(t.state)?`<button data-fm-retry="${t.id}">重试</button>`:''}${t.kind==='下载'&&t.location?`<button data-fm-reveal="${t.id}">打开保存位置</button>`:''}</div></div>${multiple?`<details data-job="${t.id}"><summary>文件明细</summary><div class="fm-file-details">${items.map(i=>`<div class="fm-item-status"><span data-no-i18n title="${esc(i.name)}">${esc(i.name)}</span><small>${esc(i.state)}</small></div>${!terminal&&i.name===t.current?`<div class="fm-item-progress"><progress value="${t.fileReceived||0}" max="${t.fileTotal||1}"></progress><small>${bytes(t.fileReceived||0)} / ${bytes(t.fileTotal||0)}</small></div>`:''}`).join('')}</div></details>`:''}</article>`;
  }).join('')||'<div class="fm-queue-empty">'+icon('download')+'<p>'+(transfers.length?'此分类暂无任务':'暂无传输任务')+'</p></div>'}</div>`;
  panel.querySelector('.fm-queue-list').scrollTop=scroll;for(const d of panel.querySelectorAll('details'))d.open=expanded.includes(d.dataset.job);if(wasOpen!==queueOpen)layout();
 }
 document.addEventListener('click',async e=>{const t=e.target.closest('button'),row=e.target.closest('[data-fm-row]');if($('#fmContext')&&!e.target.closest('#fmContext'))$('#fmContext').remove();try{if(t?.dataset.page==='files'){e.stopImmediatePropagation();return await open();}if(t?.dataset.fm){e.stopImmediatePropagation();$('#fmContext')?.remove();return await action(t.dataset.fm);}if(t?.dataset.fmPath){e.stopImmediatePropagation();return await navigate(t.dataset.fmPath);}if(t?.dataset.fmTree){e.stopImmediatePropagation();const p=t.dataset.fmTree;if(fm.expanded.has(p))fm.expanded.delete(p);else{fm.expanded.add(p);if(!fm.tree.has(p)){const d=await call('filesList',{address:fm.address,path:p});fm.tree.set(p,d.entries);}}$('#fmTree').innerHTML=treeNode('/sd','SD 卡');return;}if(t?.dataset.fmSort){e.stopImmediatePropagation();const k=t.dataset.fmSort;fm.ascending=fm.sort===k?!fm.ascending:true;fm.sort=k;render();return;}if(t?.dataset.fmFilter){e.stopImmediatePropagation();queueFilter=t.dataset.fmFilter;renderQueue();return;}for(const [data,method] of [['fmCancel','filesCancel'],['fmRetry','filesRetry'],['fmReveal','filesReveal']])if(t?.dataset[data]){e.stopImmediatePropagation();await call(method,{id:t.dataset[data]});return;}if(row)selection(row,e);if(e.target.id==='fmSelectAll'){for(const x of sorted())e.target.checked?fm.selected.add(x.path):fm.selected.delete(x.path);updateSelection();}}catch(error){toast(error.message);}},true);
 document.addEventListener('dblclick',e=>{const row=e.target.closest('[data-fm-row]');if(row){fm.selected=new Set([row.dataset.fmRow]);action('open').catch(e=>toast(e.message));}else if(e.target.closest('.fm-address'))action('address');});
 document.addEventListener('contextmenu',e=>{if(e.target.closest('#fmListArea'))context(e,e.target.closest('[data-fm-row]'));});
 document.addEventListener('input',e=>{if(e.target.id==='fmSearch'){fm.filter=e.target.value;renderRows();}});
 document.addEventListener('keydown',e=>{if(state.page!=='files'||state.drawer||state.modal)return;const input=e.target.matches('input,textarea');if(e.target.id==='fmPathInput'&&e.key==='Enter'){e.preventDefault();navigate(e.target.value);return;}if(input)return;let id;if(e.ctrlKey){id={c:'copy',x:'cut',v:'paste'}[e.key.toLowerCase()];if(e.key.toLowerCase()==='a'){e.preventDefault();sorted().forEach(x=>fm.selected.add(x.path));updateSelection();return;}}if(e.altKey)id={ArrowLeft:'back',ArrowRight:'forward',ArrowUp:'up'}[e.key];id=id||{F2:'rename',Delete:'delete',F5:'refresh',Enter:'open'}[e.key];if(e.key==='Escape'){$('#fmContext')?.remove();fm.selected.clear();updateSelection();}if(id){e.preventDefault();e.stopImmediatePropagation();action(id).catch(e=>toast(e.message));}},true);
 document.addEventListener('submit',async e=>{if(e.target.id!=='fmNameForm')return;e.preventDefault();e.stopImmediatePropagation();const b=e.target.querySelector('[type=submit]');b.disabled=true;try{await call(fm.nameAction==='mkdir'?'filesMkdir':'filesRename',{address:fm.address,directory:fm.path,path:fm.nameSource,name:$('#fmName').value});closeModal();await navigate(fm.path,false);}catch(error){$('#fmNameError').textContent=error.message;b.disabled=false;}},true);
 document.addEventListener('dragover',e=>{if(state.page==='files'&&e.dataTransfer.types.includes('Files')){e.preventDefault();$('#fmListArea')?.classList.add('drag-over');}});
 document.addEventListener('dragleave',e=>{if(!e.relatedTarget)$('#fmListArea')?.classList.remove('drag-over');});
 document.addEventListener('drop',async e=>{if(state.page!=='files')return;e.preventDefault();$('#fmListArea')?.classList.remove('drag-over');try{if(!e.dataTransfer.files.length)return;await window.desktop.uploadDropped([...e.dataTransfer.files],{address:fm.address,directory:fm.path});queueOpen=true;renderQueue();}catch(error){toast(error.message);}});
 document.addEventListener('pointerdown',e=>{if(e.button!==0||!e.target.closest('#fmListArea')||e.target.closest('tr[data-fm-row],thead,button,input'))return;const area=$('#fmListArea'),start={x:e.clientX,y:e.clientY},base=e.ctrlKey?new Set(fm.selected):new Set();const box=document.createElement('div');box.className='fm-selection-box';document.body.append(box);const move=ev=>{const left=Math.min(start.x,ev.clientX),top=Math.min(start.y,ev.clientY),right=Math.max(start.x,ev.clientX),bottom=Math.max(start.y,ev.clientY);Object.assign(box.style,{left:left+'px',top:top+'px',width:right-left+'px',height:bottom-top+'px'});fm.selected=new Set(base);area.querySelectorAll('[data-fm-row]').forEach(row=>{const r=row.getBoundingClientRect();if(r.right>left&&r.left<right&&r.bottom>top&&r.top<bottom)fm.selected.add(row.dataset.fmRow);});updateSelection();};const up=()=>{box.remove();document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',up);};document.addEventListener('pointermove',move);document.addEventListener('pointerup',up);});
 window.desktop.onEvent(({type,value})=>{if(type==='file-transfers'){const first=transfers.length===0&&value.length>0,added=value.some(t=>!transfers.some(old=>old.id===t.id)&&!['已完成','已取消','失败','已跳过'].includes(t.state));transfers=value;if(added&&queueFilter==='ended')queueFilter='active';if(first)queueOpen=true;renderQueue();}if(type==='files-changed'&&state.page==='files'&&value.address===fm.address){fm.tree.clear();navigate(fm.path,false);}});
 window.filesUI={open,relabel:render,refresh:()=>navigate(fm.path,false),back:()=>action('back'),forward:()=>action('forward')};
 call('filesTransfers').then(v=>{transfers=v;renderQueue();}).catch(()=>{});
})();
