'use strict';
const fs=require('node:fs'),fsp=fs.promises,path=require('node:path'),http=require('node:http'),crypto=require('node:crypto');
const {Transform}=require('node:stream');
const {pipeline}=require('node:stream/promises');
const device=require('./device.cjs');
const REMOTE='/sd';
function remotePath(value){const s=String(value||REMOTE).replaceAll('\\','/');if(s.includes('\0')||s.split('/').includes('..'))throw Error('文件路径无效');const p=path.posix.normalize(s);if(p!==REMOTE&&!p.startsWith(REMOTE+'/'))throw Error('仅能访问设备开放的 SD 卡');return p.replace(/\/$/,'');}
function entryName(value){const s=String(value||'').trim();if(!s||s==='.'||s==='..'||/[\\/:*?"<>|\x00-\x1f]/.test(s)||/[. ]$/.test(s)||/^(con|prn|aux|nul|com[1-9]|lpt[1-9])(\.|$)/i.test(s)||s.length>180)throw Error('名称包含不支持的字符或过长');return s;}
const join=(dir,name)=>remotePath(dir+'/'+entryName(name));
const parent=p=>path.posix.dirname(remotePath(p));
const cancelled=()=>new Error('已取消');
class Files {
 constructor({dialog,shell,window,emit,tempDir}){Object.assign(this,{dialog,shell,window,emit,tempDir});this.routes=new Map();this.jobs=[];this.running=false;this.closed=false;}
 async api(address,route,method='GET',body){return device.request(device.host(address),route,method,body,30000);}
 async devtools(address){const cached=this.routes.get(address);if(cached&&Date.now()-cached.time<15000)return cached.route;let s=await this.api(address,'/api/system/services');let d=s.services?.find(s=>s.id==='devtools');if(!d)throw Error('此操作需要设备安装 DevTools 服务');if(!d.running){await this.api(address,'/api/system/services/start?id=devtools','POST');for(let i=0;i<8;i++){await new Promise(r=>setTimeout(r,300));s=await this.api(address,'/api/system/services');d=s.services?.find(s=>s.id==='devtools');if(d?.running)break;}}if(!d?.running||!d.route_base)throw Error('DevTools 未能启动');for(const candidate of [...new Set([d.route_base+'/api','/devtools/api'])]){try{const info=await this.api(address,candidate+'/info');if(info?.ok===true){this.routes.set(address,{route:candidate,time:Date.now()});return candidate;}}catch{}}throw Error('DevTools 文件接口不可用，请在设备中更新 DevTools');}
 async op(address,action,params,method='POST'){const base=await this.devtools(address);return this.api(address,base+'/'+action+'?'+new URLSearchParams(params),method);}
 async list(address,dir=REMOTE){dir=remotePath(dir);const result=await this.api(address,'/api/system/fs/list?path='+encodeURIComponent(dir));return {path:remotePath(result.path||dir),entries:(result.entries||result.items||[]).filter(x=>x.name!=='.'&&x.name!=='..').map(x=>{const p=remotePath(x.path||dir+'/'+x.name);if(parent(p)!==dir)throw Error('设备返回了无效的子目录路径');return {name:String(x.name),path:p,is_dir:!!x.is_dir||x.type==='dir',size:Number(x.size)||0,mime:x.mime||'',modified:x.mtime||x.modified||null};})};}
 async stat(address,p){p=remotePath(p);if(p===REMOTE)return {path:p,name:'SD 卡',is_dir:true,size:0};const l=await this.list(address,parent(p));return l.entries.find(x=>x.path===p)||null;}
 async mkdir(address,p){p=remotePath(p);if(p===REMOTE)return;const old=await this.stat(address,p);if(old){if(!old.is_dir)throw Error('同名文件阻止创建目录：'+p);return;}await this.api(address,'/api/system/fs/mkdir?path='+encodeURIComponent(p),'POST');}
 async ensureDir(address,p){p=remotePath(p);const parts=p.slice(4).split('/').filter(Boolean);let root=REMOTE;for(const part of parts){root=join(root,part);await this.mkdir(address,root);}}
 async remove(address,p){p=remotePath(p);if(p===REMOTE)throw Error('不能删除 SD 卡根目录');const s=await this.stat(address,p);if(!s)return;await this.op(address,s.is_dir?'rmdir':'remove',{path:p,...(s.is_dir?{recursive:'1'}:{})},'DELETE');}
 async rename(address,p,to){p=remotePath(p);to=remotePath(to);if(p===REMOTE||to===REMOTE||to.startsWith(p+'/'))throw Error('不能移动根目录或移入自身');return this.op(address,'rename',{path:p,new_path:to});}
 async confirmDelete(address,paths){const unique=this.roots(paths);const r=await this.dialog.showMessageBox(this.window(),{type:'warning',title:'永久删除',message:'永久删除选中的 '+unique.length+' 个项目？',detail:address+'\n'+unique.slice(0,8).join('\n')+'\n设备没有回收站，文件夹内的内容也会删除。',buttons:['取消','永久删除'],defaultId:0,cancelId:0});if(r.response!==1)return false;return this.enqueue({address,kind:'删除',paths:unique});}
 roots(paths){if(!Array.isArray(paths)||!paths.length)throw Error('请先选择文件');const list=[...new Set(paths.map(remotePath))];if(list.includes(REMOTE))throw Error('不能操作 SD 卡根目录');return list.filter(p=>!list.some(q=>q!==p&&p.startsWith(q+'/')));}
 snapshot(){return this.jobs.map(j=>({id:j.id,kind:j.kind,address:j.address,name:j.name,state:j.state,total:j.total,received:j.received,speed:j.speed||0,current:j.current||'',fileReceived:j.fileReceived||0,fileTotal:j.fileTotal||0,error:j.error||'',done:j.done||0,count:j.count||0,skipped:j.skipped||0,items:j.items||[],location:j.location||'',preparing:!!j.preparing}));}
 changed(force=false){if(!force&&Date.now()-(this.lastEmit||0)<150)return;this.lastEmit=Date.now();this.emit('file-transfers',this.snapshot());}
 enqueue(spec){const j={id:crypto.randomUUID(),...spec,name:spec.name||spec.paths?.map(p=>path.posix.basename(p)).join('、')||'文件传输',state:'排队中',total:0,received:0,items:[],abort:new AbortController()};this.jobs.unshift(j);this.changed(true);setImmediate(()=>this.pump());return j.id;}
 active(){return this.jobs.some(j=>['排队中','传输中','准备中','正在保存','等待选择'].includes(j.state));}
 async pump(){if(this.running||this.closed)return;this.running=true;try{let j;while((j=this.jobs.slice().reverse().find(x=>x.state==='排队中'))&&!this.closed){try{await this.run(j);j.state=j.skipped&&j.done===0?'已跳过':'已完成';}catch(e){j.state=j.abort.signal.aborted?'已取消':'失败';j.error=e.message;}finally{j.speed=0;j.preparing=false;this.changed(true);this.emit('files-changed',{address:j.address});}}}finally{this.running=false;}}
 check(j){if(j.abort.signal.aborted||this.closed)throw cancelled();}
 cancel(id){const j=this.jobs.find(x=>x.id===id);if(j&&!['已完成','已取消','失败','已跳过'].includes(j.state)){j.abort.abort();if(j.state==='排队中')j.state='已取消';this.changed(true);}return true;}
 retry(id){const j=this.jobs.find(x=>x.id===id);if(!j||!['失败','已取消'].includes(j.state))return false;const spec={address:j.address,kind:j.kind,paths:j.paths,directory:j.directory,sources:j.sources,location:j.location,name:j.name};return this.enqueue(spec);}
 reveal(id){const j=this.jobs.find(x=>x.id===id);if(j?.kind==='下载'&&j.location)this.shell.openPath(j.location);}
 close(){this.closed=true;for(const j of this.jobs)this.cancel(j.id);}
 async conflict(j,destination,isDirectory,existsFn){const existing=await existsFn(destination);if(!existing)return destination;let decision=j.conflictChoice;if(!decision){j.state='等待选择';this.changed(true);const r=await this.dialog.showMessageBox(this.window(),{type:'question',title:'目标已存在',message:path.basename(destination)+' 已存在',detail:isDirectory&&existing.is_dir?'覆盖将合并文件夹，并逐个处理同名文件。':destination,buttons:['覆盖','跳过','自动改名','取消任务'],defaultId:1,cancelId:3,checkboxLabel:'应用到本次任务的全部冲突',checkboxChecked:false});decision=['overwrite','skip','rename','cancel'][r.response];if(r.checkboxChecked)j.conflictChoice=decision;j.state='传输中';}this.check(j);if(decision==='cancel'){j.abort.abort();throw cancelled();}if(decision==='skip')return null;if(decision==='overwrite'){if(!!existing.is_dir!==!!isDirectory)throw Error('同名项目的文件/目录类型不同，请选择自动改名：'+destination);return destination;}const ext=isDirectory?'':path.extname(destination),base=destination.slice(0,destination.length-ext.length);for(let n=2;n<10000;n++){const p=base+' ('+n+')'+ext;if(!await existsFn(p))return p;}throw Error('无法生成不重复的名称');}
 async walkRemote(address,p,callback,relative=''){const s=await this.stat(address,p);if(!s)throw Error('文件不存在：'+p);await callback(s,relative||s.name);if(s.is_dir){const list=await this.list(address,p);for(const item of list.entries)await this.walkRemote(address,item.path,callback,(relative||s.name)+'/'+item.name);}}
 async chooseUpload(address,directory,folder=false,sources){directory=remotePath(directory);if(!sources){const r=await this.dialog.showOpenDialog(this.window(),{title:folder?'选择上传文件夹':'选择上传文件',properties:folder?['openDirectory','multiSelections']:['openFile','multiSelections']});if(r.canceled)return null;sources=r.filePaths;}if(!Array.isArray(sources)||!sources.length||sources.length>1000)throw Error('请选择要上传的文件');return this.enqueue({address:device.host(address),kind:'上传',directory,sources:sources.map(p=>path.resolve(p)),name:sources.map(p=>path.basename(p)).join('、')});}
 async chooseDownload(address,paths){const r=await this.dialog.showOpenDialog(this.window(),{title:'选择下载保存位置',properties:['openDirectory','createDirectory']});if(r.canceled)return null;return this.enqueue({address:device.host(address),kind:'下载',paths:this.roots(paths),location:r.filePaths[0]});}
 paste(address,paths,directory,move){directory=remotePath(directory);paths=this.roots(paths);if(paths.some(p=>directory===p||directory.startsWith(p+'/')))throw Error('不能复制或移动到自身目录');return this.enqueue({address:device.host(address),kind:move?'移动':'复制',paths,directory});}
 async safeLocal(root,relative){const pieces=relative.replaceAll('\\','/').split('/').map(entryName);const target=path.resolve(root,...pieces);if(!target.startsWith(path.resolve(root)+path.sep))throw Error('下载路径超出保存目录');let cur=path.resolve(root);for(const piece of pieces){cur=path.join(cur,piece);try{const s=await fsp.lstat(cur);if(s.isSymbolicLink())throw Error('目标目录包含链接，请选择其他保存位置');}catch(e){if(e.code!=='ENOENT')throw e;}}return target;}
 async localStat(p){try{const s=await fsp.lstat(p);if(s.isSymbolicLink())throw Error('不覆盖链接文件');return {is_dir:s.isDirectory(),size:s.size};}catch(e){if(e.code==='ENOENT')return null;throw e;}}
 async run(j){j.state='准备中';j.preparing=true;j.received=0;j.done=0;j.skipped=0;j.started=Date.now();j.sampleAt=Date.now();j.sampleBytes=0;this.changed(true);const plans=[];
  if(j.kind==='上传'){const walk=async(local,remote)=>{this.check(j);const s=await fsp.lstat(local);if(s.isSymbolicLink())throw Error('不上传符号链接：'+path.basename(local));if(!s.isDirectory()&&!s.isFile())throw Error('不支持此文件类型');plans.push({source:local,dest:remote,is_dir:s.isDirectory(),size:s.size});if(s.isDirectory())for(const name of await fsp.readdir(local))await walk(path.join(local,name),join(remote,name));};for(const p of j.sources)await walk(p,join(j.directory,path.basename(p)));}
  else if(j.kind==='移动'||j.kind==='删除'){for(const p of j.paths){const s=await this.stat(j.address,p);if(!s)throw Error('文件不存在：'+p);plans.push({source:p,dest:j.kind==='移动'?join(j.directory,s.name):'',is_dir:s.is_dir,size:0});}}
  else {for(const p of j.paths)await this.walkRemote(j.address,p,async(s,rel)=>{this.check(j);plans.push({source:s.path,dest:j.kind==='下载'?await this.safeLocal(j.location,rel):remotePath(j.directory+'/'+rel),is_dir:s.is_dir,size:s.size});});}
  j.preparing=false;j.count=plans.length;j.total=plans.reduce((n,p)=>n+(p.is_dir?0:p.size*(j.kind==='复制'?2:1)),0);j.items=plans.map(p=>({name:path.basename(p.dest||p.source),state:'排队中',size:p.is_dir?0:p.size}));j.state='传输中';this.changed(true);const remaps=[],skips=[];
  for(let i=0;i<plans.length;i++){this.check(j);const p=plans[i],item=j.items[i];let dest=p.dest;for(const m of remaps.slice().reverse()){if(dest===m.old||dest.startsWith(m.old+(j.kind==='下载'?path.sep:'/'))){dest=m.next+dest.slice(m.old.length);break;}}j.current=item.name;j.fileTotal=p.is_dir?0:p.size*(j.kind==='复制'?2:1);j.fileReceived=0;item.state='传输中';this.changed(true);
   if(skips.some(s=>p.dest===s||p.dest.startsWith(s+(j.kind==='下载'?path.sep:'/')))){j.skipped++;item.state='已跳过';continue;}
   try{if(j.kind==='删除')await this.remove(j.address,p.source);
    else {if(j.kind==='移动'&&p.source===dest){j.skipped++;item.state='已跳过';continue;}const oldDest=dest;dest=await this.conflict(j,dest,p.is_dir,j.kind==='下载'?p=>this.localStat(p):p=>this.stat(j.address,p));if(dest===null){if(p.is_dir)skips.push(p.dest);j.skipped++;item.state='已跳过';continue;}if(p.is_dir&&oldDest!==dest)remaps.push({old:p.dest,next:dest});this.check(j);
     if(j.kind==='移动'){await this.moveResolved(j,p.source,dest);}
     else if(p.is_dir){if(j.kind==='下载')await fsp.mkdir(dest,{recursive:true});else await this.ensureDir(j.address,dest);}
     else if(j.kind==='下载'){await fsp.mkdir(path.dirname(dest),{recursive:true});await this.download(j,p.source,dest,p.size);}
     else if(j.kind==='上传'){await this.upload(j,p.source,dest,p.size);}
     else {await fsp.mkdir(this.tempDir,{recursive:true});const temp=path.join(this.tempDir,crypto.randomUUID()+'.copy');try{await this.download(j,p.source,temp,p.size);await this.upload(j,temp,dest,p.size);}finally{await fsp.rm(temp,{force:true}).catch(()=>{});}}
    }j.done++;item.state='已完成';
   }catch(e){item.state=j.abort.signal.aborted?'已取消':'失败';throw e;}finally{this.changed(true);}
  }
 }
 async moveResolved(j,source,dest){this.check(j);const old=await this.stat(j.address,dest);if(!old)return this.rename(j.address,source,dest);if(old.is_dir){for(const item of (await this.list(j.address,source)).entries){this.check(j);const target=await this.conflict(j,join(dest,item.name),item.is_dir,p=>this.stat(j.address,p));if(target===null){j.skipped++;continue;}await this.moveResolved(j,item.path,target);}if(!(await this.list(j.address,source)).entries.length)await this.remove(j.address,source);return;}const backup=join(parent(dest),'.holo-'+crypto.randomUUID().slice(0,12)+'.bak');await this.rename(j.address,dest,backup);try{await this.rename(j.address,source,dest);}catch(e){await this.rename(j.address,backup,dest);throw e;}await this.remove(j.address,backup);}
 progress(j,bytes){j.received+=bytes;j.fileReceived+=bytes;const now=Date.now(),elapsed=now-j.sampleAt;if(elapsed>=350){j.speed=(j.received-j.sampleBytes)*1000/elapsed;j.sampleAt=now;j.sampleBytes=j.received;}this.changed();}
 async response(address,route,signal){return new Promise((resolve,reject)=>{const req=http.get('http://'+device.host(address)+route,{signal,timeout:30000},res=>{if(res.statusCode!==200){res.resume();reject(Error('下载 HTTP '+res.statusCode));}else resolve(res);});req.on('timeout',()=>req.destroy(Error('设备传输超时')));req.on('error',reject);});}
 async download(j,source,dest,size){const tmp=dest+'.holo-'+crypto.randomUUID()+'.part';try{const res=await this.response(j.address,'/api/system/fs/file?path='+encodeURIComponent(source),j.abort.signal);let count=0;const meter=new Transform({transform:(c,e,cb)=>{count+=c.length;this.progress(j,c.length);cb(null,c);}});await pipeline(res,meter,fs.createWriteStream(tmp,{flags:'wx'}),{signal:j.abort.signal});if(count!==size)throw Error('下载大小与目录记录不一致，请刷新后重试');this.check(j);await fsp.rename(tmp,dest);}finally{await fsp.rm(tmp,{force:true}).catch(()=>{});}}
 async rawUpload(j,source,dest,size){return new Promise((resolve,reject)=>{const req=http.request('http://'+device.host(j.address)+'/api/system/fs/upload?path='+encodeURIComponent(dest),{method:'PUT',headers:{'Content-Type':'application/octet-stream','Content-Length':size},signal:j.abort.signal,timeout:30000},res=>{const chunks=[];let length=0;res.on('data',c=>{length+=c.length;if(length<65536)chunks.push(c);});res.on('error',reject);res.on('end',()=>{let value;try{value=JSON.parse(Buffer.concat(chunks).toString())}catch{}if(res.statusCode<200||res.statusCode>=300||value?.ok===false)reject(Error(value?.error||'上传 HTTP '+res.statusCode));else resolve();});});req.on('error',reject);req.on('timeout',()=>req.destroy(Error('设备上传超时')));(async()=>{try{for await(const chunk of fs.createReadStream(source,{highWaterMark:32768})){this.check(j);await new Promise((r,j)=>req.write(chunk,e=>e?j(e):r()));this.progress(j,chunk.length);}j.state='正在保存';this.changed(true);req.end();}catch(e){req.destroy(e);}})();});}
 async upload(j,source,dest,size){await this.ensureDir(j.address,parent(dest));await this.devtools(j.address);const temp=join(parent(dest),'.holo-'+crypto.randomUUID().slice(0,12)+'.part');let backup=null;try{await this.rawUpload(j,source,temp,size);this.check(j);const stat=await this.stat(j.address,temp);if(!stat||stat.size!==size)throw Error('设备保存的文件大小不一致');const existing=await this.stat(j.address,dest);if(existing){if(existing.is_dir)throw Error('目标是目录');backup=join(parent(dest),'.holo-'+crypto.randomUUID().slice(0,12)+'.bak');await this.rename(j.address,dest,backup);}try{await this.rename(j.address,temp,dest);}catch(e){if(backup)await this.rename(j.address,backup,dest);backup=null;throw e;}if(backup){await this.remove(j.address,backup);backup=null;}j.state='传输中';}finally{await this.remove(j.address,temp).catch(()=>{});}}
 async read(address,p){const s=await this.stat(address,p);if(!s||s.is_dir)throw Error('请选择文件');const image=/\.(png|jpe?g|gif|webp|bmp)$/i.test(p);if(s.size>(image?12:2)*1024*1024)throw Error('文件过大，请下载后打开（文本上限 2 MB，图片 12 MB）');const res=await this.response(address,'/api/system/fs/file?path='+encodeURIComponent(p),AbortSignal.timeout(15000));const parts=[];let bytes=0;for await(const c of res){bytes+=c.length;if(bytes>12*1024*1024){res.destroy();throw Error('预览文件过大');}parts.push(c);}const buf=Buffer.concat(parts);if(image){const ext=path.extname(p).slice(1).replace('jpg','jpeg');return {path:p,size:s.size,image:'data:image/'+ext+';base64,'+buf.toString('base64')};}if(buf.includes(0))throw Error('此文件不是文本，请下载后打开');return {path:p,size:s.size,text:buf.toString('utf8'),hash:crypto.createHash('sha256').update(buf).digest('hex')};}
 async saveText(address,p,text,hash){p=remotePath(p);if(Buffer.byteLength(text)>2*1024*1024)throw Error('文本超过 2 MB');const old=await this.stat(address,p);if(old&&hash){const now=await this.read(address,p);if(now.hash!==hash){const r=await this.dialog.showMessageBox(this.window(),{type:'warning',message:'设备文件已被其他操作修改，仍要覆盖？',buttons:['取消','覆盖'],defaultId:0,cancelId:0});if(r.response!==1)return null;}}else if(old){const r=await this.dialog.showMessageBox(this.window(),{type:'warning',message:'同名文件已存在，是否覆盖？',buttons:['取消','覆盖'],defaultId:0,cancelId:0});if(r.response!==1)return null;}if(this.active())throw Error('请等待传输队列结束后保存编辑');await fsp.mkdir(this.tempDir,{recursive:true});const tmp=path.join(this.tempDir,crypto.randomUUID()+'.txt');try{await fsp.writeFile(tmp,text,'utf8');const j={address,abort:new AbortController(),received:0,fileReceived:0,sampleAt:Date.now(),sampleBytes:0};await this.upload(j,tmp,p,Buffer.byteLength(text));return {hash:crypto.createHash('sha256').update(text).digest('hex'),path:p};}finally{await fsp.rm(tmp,{force:true});}}
}
module.exports={Files,remotePath,entryName,join};
