'use strict';
function syncSerialOutput(m){const key=m.device+'|'+(m.connection?.sessionId||m.connection?.address+'|'+m.connection?.port);if(key!==state.serialViewKey){state.serialViewKey=key;state.serialText=m.text||'';if($('#serialText'))$('#serialText').textContent=state.serialText;}}
function renderSerial(ports){
 const m=state.serialMonitor||{},connection=state.serial;
 drawer('串口终端','自动保存串口输出，识别死机和重启并保留异常前后文。',toolBack()+`<section class="serial-log-card"><div class="serial-log-top"><b>设备串口日志</b><label class="checkbox-row"><input type="checkbox" id="autoSerialLog" ${m.enabled!==false?'checked':''}>连接设备时自动记录串口</label></div><div class="serial-log-status"><i class="dot ${m.status==='recording'?'':'offline'}" id="serialLogDot"></i><span id="serialLogMessage"></span></div><p class="small-note">单个可用串口自动连接；多个串口时，选择下方串口并连接以记住设备绑定。断开按钮暂停本次自动连接。</p><div class="serial-log-path" id="serialLogPath" data-no-i18n></div><div id="serialLastIncident"></div><div class="pc-service-actions">${btn('串口日志文件夹','data-action="serial-log-folder"','small')}${btn('运行日志','data-tool="logs"','small')}</div></section><div class="serial-toolbar"><label class="field"><span>串口</span><select id="serialPort">${ports.length?selectOptions(ports.map(p=>[p,p]),connection?.port||m.binding):'<option value="">没有检测到串口</option>'}</select></label><label class="field"><span>波特率</span><select id="serialBaud">${selectOptions([9600,19200,38400,57600,115200,230400,460800,921600,1500000,2000000].map(n=>[n,n]),connection?.baud||m.baud||115200)}</select></label>${btn('刷新','data-tool="serial"','small')}${btn(connection?'断开':'连接',`id="serialConnectButton" data-action="${connection?'serial-close':'serial-open'}"`,'primary')}</div><p class="small-note" id="serialStatus">${connection?esc(connection.name||'')+' · '+esc(connection.address||'')+' · '+esc(connection.port):'未连接设备'}</p><pre class="terminal serial-output" id="serialText">${esc(state.serialText||'等待串口数据…')}</pre><form id="serialForm" class="serial-send"><input id="serialInput" placeholder="输入发送内容" autocomplete="off"><select id="lineEnding"><option value="lf">换行 LF</option><option value="crlf">换行 CRLF</option><option value="none">不换行</option></select><button class="btn primary">发送</button></form><div class="pc-service-actions">${btn('清空显示','data-action="serial-clear"','small')}</div>`,true);renderSerialLogStatus();
}
function renderSerialLogStatus(){
 if(!$('#serialLogMessage'))return;const m=state.serialMonitor||{},c=m.connection;
 $('#serialLogMessage').textContent=m.message||'等待 USB 串口';$('#serialLogDot').classList.toggle('offline',m.status!=='recording');$('#serialLogPath').textContent=m.file||m.path||'';$('#autoSerialLog').checked=m.enabled!==false;
 const incident=m.lastEvent;$('#serialLastIncident').innerHTML=incident?`<div class="serial-incident"><b>${esc(incident.label)}</b><span data-no-i18n>${esc(incident.device.name)} · ${esc(incident.device.ip)} · ${esc(new Date(incident.time).toLocaleString())}</span><small data-no-i18n>${esc(incident.reason)}</small></div>`:'';
 const button=$('#serialConnectButton');button.dataset.action=c?'serial-close':'serial-open';button.textContent=c?'断开':'连接';$('#serialStatus').textContent=c?`${c.name} · ${c.address} · ${c.port} · ${c.baud}`:'未连接设备';
}
document.addEventListener('change',async e=>{if(e.target.id!=='autoSerialLog')return;try{state.serialMonitor=await call('serialLogConfigure',{enabled:e.target.checked});renderSerialLogStatus();}catch(error){toast(error.message);}});
window.desktop.onEvent(({type,value})=>{
 if(type==='serial-monitor'){syncSerialOutput(value);state.serialMonitor=value;renderSerialLogStatus();}
 if(type==='device-incident'){toast(HoloI18n.translate(value.label)+' · '+value.device.name+' · '+value.port);}
 if(type==='serial-state'&&state.serialMonitor){state.serialMonitor.connection=value;renderSerialLogStatus();}
});
