'use strict';
function serviceDeviceApp(service,system=state.system){const installed=system?.apps||[];return installed.find(a=>a.id===system.current_app?.id&&service.apps.includes(a.id.toLowerCase()))||service.apps.map(id=>installed.find(a=>a.id.toLowerCase()===id)).find(Boolean);}
function serviceAppIcon(service){const app=serviceDeviceApp(service);return app?appVisual(app):appIcon(service.icon,service.color);}
async function enterServiceApp(id){const service=state.pc.services.find(s=>s.id===id);if(!service)throw Error('未知电脑服务');const address=state.prefs.active,current=await api('/api/system/state','GET',undefined,address);if(address!==state.prefs.active)return;state.system=current;const app=serviceDeviceApp(service,current);if(!app)throw Error('设备未安装对应应用');await launchApp(app.id);}
function renderPc(){
 const p=state.pc;drawer('电脑服务','相关设备应用打开后，自动启动并配置对应服务。',`<div class="pc-service-target"><span>当前设备</span><strong data-no-i18n>${esc(dev().name)}</strong><code data-no-i18n>${esc(dev().ip)}</code></div><div class="toggle-row" style="margin-bottom:16px"><span>打开应用时自动配置电脑服务</span><input type="checkbox" id="autoCompanion" ${p.autoCompanion?'checked':''}></div>${p.services.map(s=>`<section class="pc-service"><div class="pc-service-top">${serviceAppIcon(s)}<div><b>${esc(s.name)}</b><small>${esc(s.description)}</small></div>${running(s.running)}</div><p class="small-note">端口 ${s.port} · ${esc(s.message)}</p><div class="pc-service-device"><span>对应应用</span><b data-no-i18n>${esc(serviceDeviceApp(s)?.name||s.apps[0])}</b></div><div class="pc-service-actions">${btn('进入设备应用',`data-pc-device-app="${s.id}"`,'small')}${btn('设置',`data-pc-config="${s.id}"`,'pc-service-settings')}${btn('服务数据',`data-pc-page="${s.id}"`,'small')}${btn(s.running?'停止':'启动',`data-pc-${s.running?'stop':'start'}="${s.id}" ${s.external?'disabled title="服务由其他程序启动"':''}`,'small primary')}</div><label class="checkbox-row"><input type="checkbox" data-pc-autostart="${s.id}" ${s.autoStart?'checked':''}>随控制台启动</label></section>`).join('')}<p class="small-note">手动停止后会保持停止状态，重新打开相关设备应用时恢复自动配置。</p>`,true)
}
async function refreshPc(){state.pc=await call('pcStatus');if(state.drawer==='services')renderPc()}
async function openPcSettings(id){
 state.pcSetting=id;state.drawer='pc-settings';const s=state.pc.services.find(s=>s.id===id);drawer(s.name+'设置','配置会保存在本机。',`<button class="tool-back" data-drawer="services">${icon('back')}电脑服务</button><p class="small-note">正在读取…</p>`,true);
 const common=`<button class="tool-back" data-drawer="services">${icon('back')}电脑服务</button><p class="small-note">设备应用：${s.apps.map(esc).join(' / ')}<br>服务地址：http://电脑局域网 IP:${s.port}</p>${btn('重新自动配置当前设备',`data-pc-sync="${s.id}"`,'primary')}`;
 if(id==='holopet'){
  const data=await call('holopetAiStatus');if(state.pcSetting!==id||state.drawer!=='pc-settings')return;
  drawer('Holopet设置','同步 AI 工作状态到设备。',common+
  `<section class="settings-section" style="margin-top:24px"><h3>AI 状态同步</h3><div class="card" id="holopetAiStatus"></div><div class="pc-service-actions">${btn('发送测试状态','data-action="holopet-ai-test"','small')}${btn('刷新','data-action="holopet-ai-refresh"','small')}</div><p class="small-note">测试仅验证推送链路，真实接入请查看事件来源和时间。</p></section>
  <section class="settings-section"><h3>ChatGPT 账号与用量</h3><div id="holopetAccount"></div><p class="small-note">请连接与当前客户端相同的账号。登录后每分钟更新额度和使用统计，设备同步当前模型对应的额度。</p><p class="small-note">登录信息仅保存在控制台专属目录。设备只接收用量数据，不接收账号或登录凭据。</p></section>
  <section class="settings-section"><h3>本地工作任务</h3><label class="toggle-row"><span>自动同步本地任务日志</span><input id="holopetLocalSync" type="checkbox" ${data.local?.enabled!==false?'checked':''}></label><p class="small-note">直接提取当前客户端的任务事件，无需重启 ChatGPT。只同步状态相关字段，不保存或转发聊天正文。</p><p id="holopetAiLocal"></p><details><summary class="small-note">可选 Hook 接入</summary><p id="holopetAiConfig"></p>${btn('配置 Hook','data-action="holopet-ai-install"','small')}<p class="small-note">Hook 配置写入后仍需客户端加载并审查，写入成功不代表已收到事件。</p></details></section>
  <section class="settings-section"><h3>常见 AI 网页</h3><p data-no-i18n style="line-height:1.9">ChatGPT · Claude · Gemini · DeepSeek<br>Kimi · 豆包 · 通义千问 · Grok</p><p class="small-note">生成请求识别为主，页面按钮识别为补充。扩展提供手动同步与暂停开关。</p>${btn('打开浏览器扩展文件夹','data-action="holopet-ai-extension"','primary')}<ol class="small-note" style="line-height:1.9;padding-left:20px"><li>打开 Edge 或 Chrome 的扩展管理，开启开发者模式。</li><li>选择加载解压缩的扩展程序，选择打开的文件夹。</li><li>刷新 AI 网页，保持 Holopet 服务运行。</li></ol><p class="small-note">原生客户端中的普通聊天需使用对应网页版或手动同步。</p></section>
  <p class="small-note">只同步状态和来源，不发送问题、回复或工具内容。</p>${btn('打开使用说明','data-action="holopet-ai-help"','small')}`,true);renderHolopetAiStatus(data);return;
 }
 if(id==='desktop-mirror'){const data=await call('mirrorStatus');if(state.pcSetting!==id)return;const v=data.settings;drawer('桌面投屏设置','支持已连接的显示器、虚拟显示器和指定区域。',common+`<form id="mirrorForm" style="margin-top:24px"><div class="form-grid"><label class="field"><span>显示器</span><select id="mirrorMonitor">${selectOptions(data.screens.map(s=>[s.index,`${s.primary?'主显示器':'显示器'} ${s.index} · ${s.width} × ${s.height}`]),v.Monitor||v.monitor||1)}</select></label><label class="field"><span>画面适配</span><select id="mirrorFit">${selectOptions([['stretch','铺满屏幕'],['contain','完整显示'],['crop','居中裁剪']],v.Fit||v.fit||'stretch')}</select></label><label class="field"><span>帧率</span><input id="mirrorFps" type="number" min="1" max="30" value="${v.Fps||v.fps||8}"></label><label class="field"><span>JPEG 质量</span><input id="mirrorQuality" type="number" min="1" max="95" value="${v.Quality||v.quality||65}"></label></div><label class="field"><span>指定区域（留空使用整个显示器）</span><input id="mirrorRegion" placeholder="x,y,宽,高" value="${esc(v.Region||v.region||'')}"></label><button type="submit" class="btn primary">保存投屏设置</button></form>`,true);return}
 if(id==='pc-monitor'){const m=await call('monitorSnapshot');if(state.pcSetting!==id||state.drawer!=='pc-settings')return;openMonitorPanel(m,common);return}
 const details=id==='smtc-music'?'自动写入当前电脑 IP、17865 端口及状态与控制路径。':id==='holopet'?'使用 /events 推送状态；旧有 Hook 可继续向 http://127.0.0.1:17321/event 发送事件。':'保留旧 App 的 8788 兼容接口，提供 /state、/status、/health。';drawer(s.name+'设置','保留原服务协议。',common+`<p class="small-note" style="margin-top:24px">${details}</p>`,true)
}
async function showSerialWifi(){
 state.drawer='serial-wifi';drawer('串口配网','通过 USB 为设备连接 Wi-Fi。',toolBack()+'<p class="small-note">正在读取串口…</p>',true);
 const [ports,status]=await Promise.all([call('serialStatus'),call('serialWifiStatus')]);if(state.drawer!=='serial-wifi')return;state.serial=ports.connection;state.wifiStatus=status;
 drawer('串口配网','连接 USB 数据线，并在设备上打开 WiFi Setting Guide。',toolBack()+`<div class="serial-toolbar"><label class="field"><span>设备串口</span><select id="wifiSerialPort">${ports.ports.length?selectOptions(ports.ports.map(p=>[p,p]),state.serial?.port):'<option value="">没有检测到串口</option>'}</select></label><label class="field"><span>波特率</span><select id="wifiSerialBaud">${selectOptions([9600,57600,115200,230400,460800,921600].map(n=>[n,n]),state.serial?.baud||115200)}</select></label>${btn('刷新','data-tool="serial-wifi"','small')}</div><div class="pc-service-actions">${btn('打开设备配网应用','data-action="launch-wifi-guide"','small')}${btn('扫描 Wi-Fi','data-action="serial-wifi-scan"','small primary')}${btn('取消等待','data-action="serial-wifi-cancel"','small')}</div><div id="wifiSerialMessage" class="notify-card" style="display:block;line-height:1.7">${esc(status.message)}</div><div id="wifiSerialNetworks" style="max-height:220px;overflow:auto;margin:14px 0"></div><form id="serialWifiForm"><label class="field"><span>Wi-Fi 名称（SSID）</span><input id="wifiSerialSsid" maxlength="64" placeholder="选择上方热点或手动输入" required></label><label class="field"><span>Wi-Fi 密码</span><input type="password" id="wifiSerialPassword" maxlength="128" autocomplete="off" placeholder="开放网络可留空"></label><label class="checkbox-row"><input type="checkbox" id="showWifiSerialPassword">显示密码</label><button type="submit" class="btn primary">连接 Wi-Fi</button></form><p class="small-note">串口连接自动复用。设备成功联网后，读取到的 IP 会自动加入设备列表。</p>`,true);renderSerialNetworks(status)
}
function renderSerialNetworks(status){state.wifiStatus=status;const message=$('#wifiSerialMessage');if(message)message.textContent=status.message||status.status;const list=$('#wifiSerialNetworks');if(list&&Array.isArray(status.networks))list.innerHTML=status.networks.map(n=>`<button class="wifi-row" data-serial-ssid="${esc(n.ssid||n.name||'')}">${icon('wifi')}<div><b>${esc(n.ssid||n.name||'隐藏网络')}</b><small>${esc(n.rssi??n.signal??'--')} dBm</small></div>${icon('arrow')}</button>`).join('');}

function renderHolopetAiStatus(data){
 renderHolopetAccount(data.account);
 const node=$('#holopetAiStatus');if(!node)return;const last=data.last;
 const names={'openai-account':'ChatGPT 账号用量','openai-local-log':'ChatGPT / Codex 本地任务','openai-hooks':'ChatGPT / Codex','codex-hooks':'ChatGPT / Codex','chatgpt-web':'ChatGPT Web','claude-web':'Claude Web','gemini-web':'Gemini Web','deepseek-web':'DeepSeek Web','kimi-web':'Kimi Web','doubao-web':'豆包 Web','qwen-web':'通义千问 Web','grok-web':'Grok Web','ai-web-manual':'手动同步','holocubic-test':'连接测试'};
 const states={thinking:'思考中',working:'执行中',building:'协作中',notification:'等待确认',done:'已完成',error:'出错',idle:'空闲',sleeping:'休眠'};
 const received=last?.sent_at&&last.event!=='BridgeStart';
 node.innerHTML='<p><b>'+esc(data.running?'Holopet 服务运行中':'Holopet 服务未启动')+'</b></p><p><span>事件来源</span>：<b data-no-i18n>'+esc(received?(names[last.source]||last.source):'--')+'</b></p><p><span>最近状态</span>：<span>'+esc(received?(last.event==='Unrecognized'?'未识别':states[last.state]||last.state):'等待真实事件')+'</span></p><p><span>接收时间</span>：<span data-no-i18n>'+esc(received?new Date(last.sent_at).toLocaleString():'--')+'</span></p>';
 const local=$('#holopetAiLocal');if(local){const s=data.local;local.textContent=!s?.enabled?'本地任务同步已暂停':s.error||(!s.watching?'未找到本地任务日志':s.lastSent?'已收到本地任务事件':s.lastDetected?'正在同步本地任务事件':'正在监听，等待新任务');}
 if(received){const context=last.context,usage=last.usage;const number=v=>typeof v==='number'&&Number.isFinite(v);const reset=t=>number(t)?new Date(t*1000).toLocaleString():'--';node.innerHTML+='<p><span>模型</span>：<span data-no-i18n>'+esc(last.model||'--')+' · '+esc(last.effort||'--')+'</span></p><p><span>上下文占用</span>：<span data-no-i18n>'+esc(number(context?.percent)?context.percent.toFixed(1)+'% · '+Number(context.used_tokens).toLocaleString()+' / '+Number(context.window_tokens).toLocaleString()+' Tokens':'--')+'</span></p><p><span>5 小时额度已用</span>：<span data-no-i18n>'+esc(number(usage?.five_hour_percent)?usage.five_hour_percent+'%':'--')+'</span></p><p><span>5 小时额度重置</span>：<span data-no-i18n>'+esc(reset(usage?.five_hour_resets_at))+'</span></p><p><span>每周额度已用</span>：<span data-no-i18n>'+esc(number(usage?.weekly_percent)?usage.weekly_percent+'%':'--')+'</span></p><p><span>每周额度重置</span>：<span data-no-i18n>'+esc(reset(usage?.weekly_resets_at))+'</span></p>';if(!usage)node.innerHTML+='<p class="small-note">本地日志没有当前模型对应的额度数据。</p>';}
 const config=$('#holopetAiConfig');if(config)config.textContent=data.configError||(data.configured?'Hook 配置已写入，触发状态以实际事件为准':'尚未配置');
}
let holopetAccountBusy=false;
async function holopetAccountAction(method,data){if(holopetAccountBusy)return;holopetAccountBusy=true;document.querySelectorAll('#holopetAccount button').forEach(b=>b.disabled=true);try{renderHolopetAiStatus(await call(method,data))}finally{holopetAccountBusy=false;await refreshHolopetAi()}}
function renderHolopetAccount(a={}){
 const node=$('#holopetAccount');if(!node)return;const n=v=>typeof v==='number'&&Number.isFinite(v);const number=v=>n(v)?v.toLocaleString():'--';const time=v=>v?new Date(v).toLocaleString(state.prefs.uiLanguage||'zh-CN'):'--';
 const action=(label,name,primary=false)=>btn(label,`data-action="holopet-account-${name}" ${holopetAccountBusy||a.loading?'disabled':''}`,primary?'small primary':'small');
 const line=(label,value)=>'<div class="ai-account-metric"><span>'+esc(label)+'</span><strong data-no-i18n>'+esc(value)+'</strong></div>';
 let html='<div class="card ai-account-card"><b>'+esc(a.login?'等待浏览器登录':a.connected?'账号已连接':a.loading?'正在连接…':'尚未连接 ChatGPT 账号')+'</b>';
 if(a.connected)html+='<p data-no-i18n>'+esc(a.account?.email||'ChatGPT')+' · '+esc(a.account?.planType||'--')+'</p>';
 if(a.login){html+='<p class="small-note">请在官方登录页面完成登录，完成后此处自动更新。</p>';if(a.login.userCode)html+='<p><span>设备登录码</span>：<strong class="ai-login-code" data-no-i18n>'+esc(a.login.userCode)+'</strong></p>';html+='<div class="pc-service-actions">'+action('重新打开登录页','reopen',true)+action('取消登录','cancel')+'</div>'}
 else html+='<div class="pc-service-actions">'+(a.connected?action('立即刷新用量','refresh',true)+action('断开账号连接','disconnect'):action('连接 ChatGPT 账号','connect',true)+action('使用设备码登录','device'))+'</div>';
 if(a.error)html+='<p class="small-note ai-account-error">'+esc(a.error)+'</p>';html+='</div>';
 if(a.connected){
  html+='<div class="ai-quota-list">';const entries=Object.entries(a.limits||{});if(!entries.length)html+='<p class="small-note">额度暂不可用，将自动重试</p>';
  for(const [id,limit]of entries){html+='<div class="ai-quota-card"><b data-no-i18n>'+esc(limit.limitName||(id==='codex'?'ChatGPT / Codex':id==='codex_bengalfox'?'GPT-5.3-Codex-Spark':id))+'</b>';for(const w of [limit.primary,limit.secondary].filter(Boolean)){const label=w.windowDurationMins===300?'5 小时':w.windowDurationMins===10080?'每周':w.windowDurationMins===1440?'每天':'额度周期';const pct=n(w.usedPercent)?Math.max(0,Math.min(100,w.usedPercent)):null;
   html+='<div class="ai-quota-row"><span>'+label+'</span><span><span>已用</span> <b data-no-i18n>'+esc(pct===null?'--':pct+'%')+'</b> · <span>剩余</span> <b data-no-i18n>'+esc(pct===null?'--':Number((100-pct).toFixed(2))+'%')+'</b></span></div><progress max="100" value="'+(pct||0)+'" aria-label="'+label+'"></progress><p class="small-note"><span>重置时间</span>：<span data-no-i18n>'+esc(time(w.resetsAt?w.resetsAt*1000:null))+'</span></p>';
  }html+='</div>'}html+='</div><p class="small-note"><span>额度更新时间</span>：<span data-no-i18n>'+esc(time(a.updatedAt))+'</span></p>';
  const stats=a.stats?.summary||{};html+='<h4>Token 使用统计</h4><div class="ai-account-grid">'+line('累计 Token',number(stats.lifetimeTokens))+line('单日最高 Token',number(stats.peakDailyTokens))+line('连续使用天数',number(stats.currentStreakDays))+line('最长连续天数',number(stats.longestStreakDays))+line('最长任务（秒）',number(stats.longestRunningTurnSec))+'</div>';
  const daily=[...(a.stats?.dailyUsageBuckets||[])].sort((x,y)=>y.startDate.localeCompare(x.startDate)).slice(0,7);if(daily.length)html+='<details class="ai-daily"><summary>最近每日用量</summary>'+daily.map(d=>'<div class="ai-quota-row" data-no-i18n><span>'+esc(d.startDate)+'</span><b>'+esc(number(d.tokens))+' Tokens</b></div>').join('')+'</details>';
  html+='<p class="small-note"><span>统计更新时间</span>：<span data-no-i18n>'+esc(time(a.statsUpdatedAt))+'</span></p>';if(a.statsError)html+='<p class="small-note">'+esc(a.statsError)+'</p>';html+='<p class="small-note">未返回的统计显示为 --。额度重置时间不是订阅到期日，接口暂不提供订阅到期日。</p>';
 }
 // Avoid replacing focused controls or collapsing daily details on each status poll.
 const key=JSON.stringify([a,holopetAccountBusy]);if(node.dataset.renderKey!==key){const expanded=node.querySelector('.ai-daily')?.open;node.innerHTML=html;node.dataset.renderKey=key;if(expanded&&node.querySelector('.ai-daily'))node.querySelector('.ai-daily').open=true;}
}
let holopetStatusBusy=false;
async function refreshHolopetAi(){if(holopetStatusBusy||state.drawer!=='pc-settings'||state.pcSetting!=='holopet')return;holopetStatusBusy=true;try{const data=await call('holopetAiStatus');if(state.drawer==='pc-settings'&&state.pcSetting==='holopet')renderHolopetAiStatus(data)}finally{holopetStatusBusy=false}}
setInterval(()=>{if(document.visibilityState==='visible')refreshHolopetAi().catch(()=>{})},2500);

const monitorUi={snapshot:null,bindings:{},dirty:false,saving:false,polling:false,request:0,groups:new Map(),rows:new Map(),mappingRows:new Map()};
function monitorActive(){return state.drawer==='pc-settings'&&state.pcSetting==='pc-monitor'&&!!$('#monitorPanel');}
function monitorText(value){return window.HoloI18n?.translate(String(value??''))??String(value??'');}
function monitorValue(value,unit=''){if(typeof value!=='number'||!Number.isFinite(value))return '--';return value.toLocaleString(state.prefs.uiLanguage||'zh-CN',{maximumFractionDigits:Math.abs(value)>=1000?0:Math.abs(value)>=10?1:2})+(unit?' '+(unit==='C'?'°C':unit):'');}
function monitorTime(value){const date=new Date(typeof value==='number'&&value<1e12?value*1000:value);return value&&Number.isFinite(date.getTime())?date.toLocaleTimeString(state.prefs.uiLanguage||'zh-CN'):'--';}
function monitorSource(source){return source==='automatic'?'自动汇总':source||'--';}
function monitorCategory(reading){const type=String(reading.hardwareType||'').toLowerCase();if(type==='summary')return '自动汇总';if(type.includes('cpu'))return 'CPU';if(/gpu|graphics/.test(type))return '显卡';if(/memory|ram/.test(type))return '内存';if(/motherboard|mainboard|superio/.test(type))return '主板';if(/storage|disk|hdd|ssd/.test(type))return '硬盘';if(/network|nic/.test(type))return '网络';if(/cooler|controller|fan/.test(type))return '风扇与控制器';if(/system|computer/.test(type))return '系统';return '其他';}
function monitorSetText(node,value){if(node&&node.textContent!==String(value??''))node.textContent=value??'';}
function openMonitorPanel(snapshot,common){
 monitorUi.snapshot=null;monitorUi.bindings={...(snapshot.settings?.bindings||{})};monitorUi.dirty=false;monitorUi.groups.clear();monitorUi.rows.clear();monitorUi.mappingRows.clear();monitorUi.request++;
 drawer('电脑监控设置','查看完整传感器，并选择发送到设备的读数。',common+`<div id="monitorPanel"><section class="settings-section"><div class="monitor-section-head"><h3>采集来源</h3>${btn('刷新','data-action="monitor-refresh"','small')}</div><div id="monitorProviders" class="monitor-providers"></div><p id="monitorError" class="error-note" role="status"></p><p class="small-note">部分温度与功耗需要管理员传感器权限。</p>${btn('启动管理员传感器','data-action="monitor-elevate"','small')}</section><section class="settings-section"><div class="monitor-section-head"><h3>全部传感器</h3><span id="monitorCount" class="small-note" data-no-i18n></span></div><div class="monitor-filter"><label class="field"><span>搜索传感器</span><input id="monitorSearch" type="search" placeholder="硬件、传感器名称或来源" autocomplete="off"></label><label class="field"><span>硬件分类</span><select id="monitorCategory"><option value="">全部硬件</option></select></label></div><div id="monitorReadings" class="monitor-readings" role="region" aria-label="全部传感器" tabindex="0"></div><p id="monitorEmpty" class="small-note" hidden>没有匹配的传感器</p><p class="small-note">读数为 0 时正常显示；暂时无数据的传感器显示 --。</p></section><details class="monitor-mapping"><summary>设备字段映射</summary><p class="small-note">自动选择适合的读数，也可指定显卡、硬盘或风扇。只列出单位相同的传感器。</p><div id="monitorMappings"></div><div class="monitor-save-bar"><span id="monitorDirty" class="small-note" role="status">映射已保存</span><div class="pc-service-actions">${btn('全部设为自动','data-action="monitor-reset"','small')}${btn('保存设备映射','data-action="monitor-save"','small primary')}</div></div></details></div>`,true);
 renderMonitorSnapshot(snapshot);
}
function renderMonitorProviders(providers){
 const node=$('#monitorProviders');if(!node)return;const html=providers.map(p=>{const status=!p.enabled?'未启用':p.available?'可用':'暂不可用';return `<div class="monitor-provider"><div><b data-no-i18n>${esc(p.name||p.id)}</b><span class="monitor-provider-state ${p.enabled&&p.available?'available':''}">${status}</span></div><p class="small-note">${esc(p.status||status)}</p><small><span>更新时间</span> <span data-no-i18n>${esc(monitorTime(p.timestamp))}</span></small></div>`;}).join('')||'<p class="small-note">暂无采集来源</p>';if(node.dataset.html!==html){node.innerHTML=html;node.dataset.html=html;}
}
function renderMonitorSnapshot(snapshot){
 if(!monitorActive())return;monitorUi.snapshot=snapshot;if(!monitorUi.dirty&&!monitorUi.saving)monitorUi.bindings={...(snapshot.settings?.bindings||{})};
 renderMonitorProviders(snapshot.providers||[]);monitorSetText($('#monitorError'),'');const readings=Array.isArray(snapshot.readings)?snapshot.readings:[];
 const present=new Set(),groupKeys=new Set(),categories=new Set(),list=$('#monitorReadings');
 for(const reading of readings){
  if(!reading||typeof reading.id!=='string')continue;present.add(reading.id);const category=monitorCategory(reading);categories.add(category);const groupKey=JSON.stringify([reading.hardwareId||'',reading.hardwareName||'',reading.hardwareType||'']);groupKeys.add(groupKey);let group=monitorUi.groups.get(groupKey);
  if(!group){group=document.createElement('details');group.className='monitor-hardware';group.open=category!=='自动汇总';group.innerHTML=`<summary><strong data-no-i18n>${esc(reading.hardwareName||reading.hardwareId||'--')}</strong><span>${esc(category)}</span></summary><p class="monitor-hardware-id" data-no-i18n>${esc(reading.hardwareId||'--')} · ${esc(reading.hardwareType||'--')}</p><div class="monitor-sensor-list"></div>`;list.appendChild(group);monitorUi.groups.set(groupKey,group);}
  let row=monitorUi.rows.get(reading.id);if(!row){row=document.createElement('div');row.className='monitor-sensor-row';row.innerHTML='<div class="monitor-sensor-name"><b data-no-i18n></b><small data-no-i18n></small></div><div class="monitor-sensor-result"><strong data-no-i18n></strong><small><span class="monitor-sensor-source"></span><span data-no-i18n class="monitor-sensor-time"></span></small></div>';monitorUi.rows.set(reading.id,row);}
  const parent=group.querySelector('.monitor-sensor-list');if(row.parentElement!==parent)parent.appendChild(row);row.dataset.category=category;row.dataset.search=[reading.hardwareName,reading.hardwareId,reading.hardwareType,reading.name,reading.sensorType,reading.source,category].join(' ').toLowerCase();
  if(category==='自动汇总')monitorSetText(group.querySelector('summary strong'),monitorText(reading.hardwareName||'自动汇总'));
  monitorSetText(row.querySelector('.monitor-sensor-name b'),reading.id.startsWith('auto:')?monitorText(reading.name||reading.id):reading.name||reading.id);monitorSetText(row.querySelector('.monitor-sensor-name small'),reading.sensorType||'--');row.title=reading.id;
  monitorSetText(row.querySelector('.monitor-sensor-result strong'),monitorValue(reading.value,reading.unit));monitorSetText(row.querySelector('.monitor-sensor-source'),monitorSource(reading.source));monitorSetText(row.querySelector('.monitor-sensor-time'),monitorTime(reading.timestamp));row.classList.toggle('unavailable',typeof reading.value!=='number'||!Number.isFinite(reading.value));
 }
 for(const [id,row]of monitorUi.rows)if(!present.has(id)){row.remove();monitorUi.rows.delete(id);}for(const [key,group]of monitorUi.groups)if(!groupKeys.has(key)){group.remove();monitorUi.groups.delete(key);}
 const categorySelect=$('#monitorCategory');const categoryKey=JSON.stringify([...categories].sort());if(categorySelect.dataset.items!==categoryKey&&document.activeElement!==categorySelect){const selected=categorySelect.value;categorySelect.innerHTML='<option value="">全部硬件</option>'+[...categories].sort().map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');categorySelect.value=categories.has(selected)?selected:'';categorySelect.dataset.items=categoryKey;}
 filterMonitorReadings();renderMonitorMappings(snapshot);updateMonitorDirty();
}
function filterMonitorReadings(){
 if(!monitorActive())return;const query=($('#monitorSearch').value||'').trim().toLowerCase(),category=$('#monitorCategory').value;let count=0;
 for(const row of monitorUi.rows.values()){row.hidden=!!((category&&row.dataset.category!==category)||(query&&!row.dataset.search.includes(query)));if(!row.hidden)count++;}
 for(const group of monitorUi.groups.values())group.hidden=![...group.querySelectorAll('.monitor-sensor-row')].some(row=>!row.hidden);
 monitorSetText($('#monitorCount'),count+' / '+monitorUi.rows.size);$('#monitorEmpty').hidden=count>0;
}
function renderMonitorMappings(snapshot){
 const host=$('#monitorMappings'),present=new Set(),readings=(snapshot.readings||[]).filter(r=>typeof r.id==='string'&&!r.id.startsWith('auto:'));const statusLabels={automatic:'自动选择',mapped:'已指定传感器',unavailable:'暂不可用',missing:'传感器已断开', 'unit-mismatch':'单位不匹配'};
 for(const mapping of snapshot.mappings||[]){
  present.add(mapping.key);let row=monitorUi.mappingRows.get(mapping.key);if(!row){row=document.createElement('div');row.className='monitor-mapping-row';row.innerHTML=`<label class="field"><span class="monitor-mapping-label">${esc(mapping.label||mapping.key)}</span><select data-monitor-binding="${esc(mapping.key)}" aria-label="${esc(mapping.label||mapping.key)}"></select></label><div class="monitor-mapping-result"><strong data-no-i18n></strong><small></small></div>`;host.appendChild(row);monitorUi.mappingRows.set(mapping.key,row);}
  const select=row.querySelector('select'),selected=monitorUi.bindings[mapping.key]||'',available=readings.filter(r=>String(r.unit||'')===String(mapping.unit||''));
  const candidates=available.map(r=>[r.id,`${r.hardwareName||r.hardwareId||'--'} · ${r.name||r.id} · ${r.source||'--'} · ${r.hardwareId||r.id}`]);const optionsKey=JSON.stringify([candidates,selected,window.HoloI18n?.language]);
  if(select.dataset.options!==optionsKey&&document.activeElement!==select){select.innerHTML=`<option value="">${esc(monitorText('自动选择（推荐）'))}</option>`+candidates.map(([id,label])=>`<option data-no-i18n value="${esc(id)}">${esc(label)}</option>`).join('');if(selected&&!available.some(r=>r.id===selected))select.insertAdjacentHTML('beforeend',`<option data-no-i18n value="${esc(selected)}">${esc(monitorText('当前映射不可用'))} · ${esc(selected)}</option>`);select.value=selected;select.dataset.options=optionsKey;}
  select.disabled=monitorUi.saving;
  const saved=mapping.sensorId||'',changed=selected!==saved;monitorSetText(row.querySelector('.monitor-mapping-result strong'),monitorValue(mapping.value,mapping.unit));monitorSetText(row.querySelector('.monitor-mapping-result small'),changed?'待保存':`${monitorText(statusLabels[mapping.status]||mapping.status||'--')} · ${monitorText(monitorSource(mapping.source))}`);
 }
 for(const [key,row]of monitorUi.mappingRows)if(!present.has(key)){row.remove();monitorUi.mappingRows.delete(key);}
}
function updateMonitorDirty(){if(!monitorActive())return;monitorSetText($('#monitorDirty'),monitorUi.saving?'正在保存映射…':monitorUi.dirty?'映射已修改，点击保存后生效':'映射已保存');$('#monitorDirty').classList.toggle('settings-dirty',monitorUi.dirty);document.querySelectorAll('[data-action="monitor-save"],[data-action="monitor-reset"]').forEach(b=>b.disabled=monitorUi.saving);}
async function refreshMonitorSnapshot(){
 if(!monitorActive()||monitorUi.polling||monitorUi.saving)return;monitorUi.polling=true;const request=++monitorUi.request;try{const snapshot=await call('monitorSnapshot');if(request===monitorUi.request&&monitorActive()&&!monitorUi.saving)renderMonitorSnapshot(snapshot);}catch(error){if(request===monitorUi.request&&monitorActive())monitorSetText($('#monitorError'),error.message);}finally{monitorUi.polling=false;}
}
async function saveMonitorBindings(){
 if(!monitorActive()||monitorUi.saving)return;monitorUi.saving=true;const bindings={...monitorUi.bindings},request=++monitorUi.request;updateMonitorDirty();renderMonitorMappings(monitorUi.snapshot);
 try{const snapshot=await call('monitorConfigure',{bindings});if(request===monitorUi.request){monitorUi.dirty=false;monitorUi.bindings={...(snapshot.settings?.bindings||bindings)};monitorUi.saving=false;if(monitorActive())renderMonitorSnapshot(snapshot);}toast('设备传感器映射已保存');}finally{monitorUi.saving=false;if(monitorActive()){updateMonitorDirty();renderMonitorMappings(monitorUi.snapshot);}}
}
function resetMonitorBindings(){if(!monitorActive()||monitorUi.saving)return;monitorUi.bindings={};monitorUi.dirty=true;renderMonitorMappings(monitorUi.snapshot);updateMonitorDirty();}
document.addEventListener('change',event=>{const element=event.target;if(element.id==='monitorCategory')filterMonitorReadings();if(element.dataset.monitorBinding&&!monitorUi.saving){const key=element.dataset.monitorBinding;if(element.value)monitorUi.bindings[key]=element.value;else delete monitorUi.bindings[key];monitorUi.dirty=true;renderMonitorMappings(monitorUi.snapshot);updateMonitorDirty();}});
document.addEventListener('input',event=>{if(event.target.id==='monitorSearch')filterMonitorReadings();});
document.addEventListener('focusout',event=>{if(event.target.dataset.monitorBinding&&monitorActive())renderMonitorMappings(monitorUi.snapshot);});
setInterval(()=>{if(document.visibilityState==='visible')refreshMonitorSnapshot().catch(()=>{});},2500);
