name: build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x
      - name: Restore
        run: dotnet restore .\src\Clocteck.CubicCenter\Clocteck.CubicCenter.csproj
      - name: Build
        run: dotnet build .\src\Clocteck.CubicCenter\Clocteck.CubicCenter.csproj -c Release --no-restore
